config/routes.rb
Rails.application.routes.draw do
  resources :items, except: :edit

  root to: 'top#index'
  get 'top/index'

  devise_for :users, controllers: { omniauth_callbacks: 'authentication' }
  devise_scope :user do
    get 'sign_in', to: 'authentication#login', as: :new_user_session
    delete 'sign_out', to: 'authentication#logout', as: :destroy_user_session
  end

end

app/models/dotenv_config.rb
class DotenvConfig
  class << self
    def devise_secret_key
      ENV['DEVISE_SECRET_KEY'] || ''
    end

    def omniauth_provider
      provider = ENV['OMNIAUTH_PROVIDER']
      if provider
        provider.to_sym
      else
        :twitter
      end
    end

    def omniauth_args
      args = ENV['OMNIAUTH_ARGS']
      if args
        JSON.parse(args)
      else
        nil
      end
    end
  end
end

app/models/item.rb
require 'open-uri'
class Item < ActiveRecord::Base
  belongs_to :user

  attr_accessor :url

  validates_uniqueness_of :asin
  validates_presence_of :release_date

  default_scope { includes(:user).order('release_date DESC') }
  scope :recent, -> { where(arel_table[:release_date].gt 1.months.ago) }

  UserAgent = 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0)'

  def to_ics(host)
    event = Icalendar::Event.new
    event.dtstart = Icalendar::Values::Date.new(self.release_date, {'TZID' => ['Asia/Tokyo']})
    event.dtstamp = self.updated_at
    event.summary = self.title
    event.url = self.amazon_url
    event.description = self.amazon_url
    event.uid = "#{Digest::MD5.hexdigest(self.amazon_url)}@#{host}"
    event
  end

  def amazon_url
    "http://www.amazon.co.jp/gp/product/#{self.asin}/?tag=mallowlabs-22"
  end

  def self.from_url(url)
    asin = url_to_asin(url.to_s)
    asin_to_item_with_retry(asin)
  end

  def self.url_to_asin(url)
    doc = Nokogiri::HTML(OpenURI.open_uri(url, 'User-Agent' => UserAgent))
    doc.css("#ASIN").first["value"] rescue nil
  end

  def self.asin_to_item(asin)
    item = Item.new
    res = Amazon::Ecs.item_lookup(asin, {response_group: 'Medium', country: 'jp'}).first_item
    item.asin = res.get('ASIN')
    item.title = res.get('ItemAttributes/Title')
    item.release_date = res.get('ItemAttributes/ReleaseDate') || res.get('ItemAttributes/PublicationDate')
    item.thumb_url = res.get('ImageSets/ImageSet/SmallImage/URL')
    item
  end

  def self.asin_to_item_with_retry(asin)
    retry_count = 0
    begin
      return self.asin_to_item(asin)
    rescue => e
      retry_count += 1
      Rails.logger.error e.message
      if retry_count < 5
        sleep(3)
        retry
      end
    end
    return nil
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :item
  devise :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_filter :authenticate_user!

  def login
    redirect_to root_path
  end

  define_method ENV['OMNIAUTH_PROVIDER'] do
    oauth = request.env['omniauth.auth']
    user = User.where(nickname: oauth.info.nickname).first
    if user
      user.name = oauth.info.name
    else
      user = User.new(name: oauth.info.name, nickname: oauth.info.nickname)
    end
    user.save
    sign_in_and_redirect user, event: :authentication
  end

  def logout
    sign_out current_user
    redirect_to root_path
  end

  def failure
    redirect_to root_path, alert: t(:error_authentication_failed)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :update, :destroy]
  before_action :validate_user, only: [:create, :new, :destroy]

  # GET /items
  # GET /items.json
  # GET /items.ics
  def index
    @items = Item.recent
    respond_to do |format|
      format.html
      format.json
      format.ics do
        calendar = Icalendar::Calendar.new
        calendar.append_custom_property('X-WR-CALNAME', "amzn-ics")
        @items.each do |item|
          calendar.add_event(item.to_ics(request.host))
        end
        calendar.publish
        render text: calendar.to_ical
      end
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.from_url(item_params[:url])
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    return render status: 403 if @item.user != current_user
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:url)
    end

    def validate_user
      return redirect_to :root if current_user.nil?
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    if user_signed_in?
      redirect_to controller: :items
      return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    not current_user.nil?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def short(time)
    time.strftime("%F")
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/items/_form.html.slim
= form_for @item, html: {class: 'form-inline'} do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.label :url, class: 'sr-only'
    = f.url_field :url, class: 'form-control', style: 'width: 640px',  placeholder: 'URL'
  = f.submit class: 'btn btn-primary', value: 'Add'

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @item
'|
= link_to 'Back', items_path

app/views/items/index.html.slim
h4 All items

.clearfix
  .pull-left
    = link_to 'New Item', new_item_path, class: 'btn btn-default'
  .pull-right
    = link_to 'Calendar link', {format: :ics}, class: 'btn btn-default'

br

table.table.table-bordered
  thead
    tr
      th Release
      th Image
      th Title
      th

  tbody
    - @items.each do |item|
      tr
        td = short(item.release_date)
        td = item.thumb_url.nil? ? '' : image_tag(item.thumb_url, class: 'thumb', alt: item.title, title: item.title)
        td = link_to item.title, item.amazon_url
        td
          - if item.user == current_user
            = link_to 'Destroy', item, data: {:confirm => 'Are you sure?'}, :method => :delete, class: 'btn btn-danger'

app/views/items/new.html.slim
h4 New item

== render 'form'

br
= link_to 'Back', items_path, class: 'btn btn-default'

app/views/items/show.html.slim
p#notice = notice

p
  strong User:
  = @item.user_id
p
  strong Asin:
  = @item.asin
p
  strong Title:
  = @item.title
p
  strong Thumb url:
  = @item.thumb_url
p
  strong Release date:
  = @item.release_date

= link_to 'Back', items_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t(:app_title)
    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = favicon_link_tag 'favicon.png', rel: 'shortcut icon'

    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    nav.navbar.navbar-fixed-top.navbar-default role='navigation'
      .container
        .navbar-header
          = link_to t(:app_title), {controller: 'top'}, class: 'navbar-brand'
          button.navbar-toggle type='button' data-toggle='collapse' data-target='#nav-content'
            span.icon-bar
            span.icon-bar
            span.icon-bar

        #nav-content.collapse.navbar-collapse
          - if user_signed_in?
            ul.nav.navbar-nav
              li= link_to "Top", controller: :top
            ul.nav.navbar-nav.pull-right
              li.dropdown
                a.dropdown-toggle data-toggle='dropdown' role='button' href="#" Account
                ul.dropdown-menu role='menu'
                  li role='presentation'
                    = link_to destroy_user_session_path, method: :delete do
                      span.glyphicon.glyphicon-log-out
                      = t(:button_sign_out)

    .container
      - if notice
        p.alert.alert-success = notice
      - if alert
        p.alert.alert-danger = alert

      = yield

      footer
        p &copy; 2015 mallowlabs

app/views/top/index.html.slim
.jumbotron
  .content
    .text-center
      h1= t(:app_title)
      h2= t(:sub_title)
      = form_tag user_omniauth_authorize_path(DotenvConfig.omniauth_provider), method: 'post' do
        button.btn.btn-primary.btn-large
          span.glyphicon.glyphicon-log-in
          = t(:button_sign_in)